# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCli < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "0.12.0-next"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/frontastic-cli-0.12.0/frontastic-cli_0.12.0_darwin_amd64.tar.gz"
    sha256 "31ae3440d048cf3a49c52eabc4adc1ad4af79379fb8c95f83ee1f70e920695f1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/frontastic-cli-0.12.0/frontastic-cli_0.12.0_linux_amd64.tar.gz"
      sha256 "c83680215be6303a5c03520b9991d649615705ad706148852956e53aa83f6f79"
    end
  end

  def install
    bin.install "frontastic"
  end
end
