# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCli < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "1.22.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/1.22.0/frontastic-cli_1.22.0_darwin_arm64.tar.gz"
      sha256 "c4222ef6acb0a869aba1a86c1bd25e4ed795b16ab7c71ed92f327097523b79d8"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/1.22.0/frontastic-cli_1.22.0_darwin_amd64.tar.gz"
      sha256 "bc82877af5a6344bd6a24ddf036a632030fafa1fba0ec82dc145041782c26879"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/1.22.0/frontastic-cli_1.22.0_linux_amd64.tar.gz"
      sha256 "f78486a44c4fb876ccd924beb4a1d8c61c2d11b0d12c1a7b3b3db39ae1d176ea"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
  end

  conflicts_with "frontastic-cli-pre"
end
