# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCliPre < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "2.0.5-pre"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FrontasticGmbH/frontastic-cli-pre/releases/download/2.0.5-pre/frontastic-cli-pre_2.0.5-pre_darwin_arm64.tar.gz"
      sha256 "b06be449daf675be2cb4c7ae1d6917103266c5f00d43f813e997e20a834d406a"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli-pre/releases/download/2.0.5-pre/frontastic-cli-pre_2.0.5-pre_darwin_amd64.tar.gz"
      sha256 "8df3cba09a6bf58335ca05e10a272614eb1d1fcbeb27aae0f5266cbd53f73e46"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli-pre/releases/download/2.0.5-pre/frontastic-cli-pre_2.0.5-pre_linux_amd64.tar.gz"
      sha256 "7bff5221ce4c14f257f6da0f1fac6c5ea8b00d8be74d8e73760007305d9fdd4a"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
  end

  conflicts_with "frontastic-cli"
end
