# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCliEa < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "2021.03.08.08.27"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FrontasticGmbH/frontastic-cli-ea/releases/download/2021.03.08.08.27/frontastic-cli-ea_2021.03.08.08.27_ea_darwin_amd64.tar.gz"
    sha256 "1299e755673b7584de49024048e57f6f7fb5b9c67d998e51f296e1f530d3c33d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/FrontasticGmbH/frontastic-cli-ea/releases/download/2021.03.08.08.27/frontastic-cli-ea_2021.03.08.08.27_ea_linux_amd64.tar.gz"
    sha256 "bad0c9821812e6edc88dd06dc92684176dd3f2e97b94000303a719ed237c9f78"
  end

  def install
    bin.install "frontastic-ea"
    prefix.install Dir["*"]
  end
end
