# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCliEa < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "frontastic-cli-ea-0.20.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FrontasticGmbH/frontastic-cli-ea/releases/download/frontastic-cli-ea-0.20.9/frontastic-cli-ea_ea-0.20.9_ea_darwin_amd64.tar.gz"
    sha256 "561b49110a0d180328ea719696f52247a496ecf243f9db10b88e99a8ac010c9d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/FrontasticGmbH/frontastic-cli-ea/releases/download/frontastic-cli-ea-0.20.9/frontastic-cli-ea_ea-0.20.9_ea_linux_amd64.tar.gz"
    sha256 "3a6ff0117ad3243635d566b55b4a28bfac756a1c73ac5c97658bd6c745ef45a2"
  end

  def install
    bin.install "frontastic-ea"
    prefix.install Dir["*"]
  end
end
