# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCliPre < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "frontastic-cli-1.4.2-pre"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli-pre/releases/download/frontastic-cli-1.4.2-pre/frontastic-cli-pre_1.4.2-pre_darwin_amd64.tar.gz"
      sha256 "328e134d3e557dee3d997865c2403e7b8aa28ed5dd215b188b54c76cfb3c4efb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/FrontasticGmbH/frontastic-cli-pre/releases/download/frontastic-cli-1.4.2-pre/frontastic-cli-pre_1.4.2-pre_darwin_arm64.tar.gz"
      sha256 "1dadc8f0d4582a859d27be53b4db7acb5389bd58374a32b7d4bf9373065e5afc"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli-pre/releases/download/frontastic-cli-1.4.2-pre/frontastic-cli-pre_1.4.2-pre_linux_amd64.tar.gz"
      sha256 "c73ca1b89d1750c03a683592874d2c0430af218e67026ecdf9f1c500ca8bb02d"
    end
  end

  conflicts_with "frontastic-cli"

  def install
    bin.install "frontastic"
    prefix.install Dir["*"]
  end
end
