# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrontasticCli < Formula
  desc ""
  homepage "https://frontastic.cloud"
  version "2.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/2.0.5/frontastic-cli_2.0.5_darwin_arm64.tar.gz"
      sha256 "ee404c67657f09e1deb48de2772c915488ed757290802f1d158630450553718c"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/2.0.5/frontastic-cli_2.0.5_darwin_amd64.tar.gz"
      sha256 "15e2069a5bc872cc69c7fa979b39c95b12c7ff945250c2f51b6619dd9b58a498"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FrontasticGmbH/frontastic-cli/releases/download/2.0.5/frontastic-cli_2.0.5_linux_amd64.tar.gz"
      sha256 "f62296d36016737c4de1bb9866a851874150898b274da79eea3051b254f0fe81"

      def install
        bin.install "frontastic"
        prefix.install Dir["*"]
        ohai "\n\nRun 'frontastic init' to get started.\n"
      end
    end
  end

  conflicts_with "frontastic-cli-pre"
end
